### ISSUE TITLE
Question: Random Sequence?

### ISSUE THREAD

**Issue by Smokingenius** [cyphunk/JTAGenum#17]
@cyphunk I was curious, why is the pattern 0110011101001101101000010111001001 (listed in source code as random) used to find the JTAG sequence? Was this just an arbitrary sequence, or were other sequences tried and this worked the best? 

Regards.

**Comment by cyphunk** [comment]
I'm sorry for my delayed response.

The pattern was chosen entirely at random. No other sequences have been tried.
