### ISSUE TITLE
Problem with running on arduino nano esp32.

### ISSUE THREAD

**Issue by p4ntek** [cyphunk/JTAGenum#24]
Hello,
First error repaired with:
`#if defined(AVR)
#include <avr/pgmspace.h>
else
#include <pgmspace.h>
#endif
`
Second is:
"Compilation error: 'class EspClass' has no member named 'wdtFeed'"
But there are others too:

![Zrzut ekranu z 2023-10-23 16-15-04](https://github.com/cyphunk/JTAGenum/assets/13277620/69a6e56f-63dd-4f6f-ac16-473f219b363c)
![Zrzut ekranu z 2023-10-23 16-14-44](https://github.com/cyphunk/JTAGenum/assets/13277620/e6fa66b8-fac2-4ad0-b6c7-aa55f26008fd)

**Comment by p4ntek** [comment]
I've read on other sites. At least one error is caused by "PULLUP" name conflicts with library.
Don't know how about "wdtFeed" error.

**Comment by p4ntek** [comment]
Im not expert but i think
Changing:

#include <avr/pgmspace.h>
to:
#ifdef ARDUINO_ARCH_AVR
#include <avr/pgmspace.h>
#else
#include <pgmspace.h>
#endif

Changing everywhere "PULLUP" to example "JTAG_PULLUP"

Changing:

#elif defined(ESP_H)       // ESP8266 Wemos D1 Mini. if properly not set may trigger watchdog
 byte       pins[] = {  D1 ,  D2 ,  D3 ,  D4 ,  D5 ,  D6 ,  D7 ,  D8  };
 String pinnames[] = { "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8" };

to

#elif defined(ESP32) //nano esp32 - not sure if correct pinout
 byte       pins[] = {  D2 ,  D3 ,  D4 ,  D5 ,  D6 ,  D7 ,  D8 ,  D9 , D10 , D11 , D12  };
 String pinnames[] = { "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9"," D10", "D11", " D12" };
#elif defined(ESP_H)       // ESP8266 Wemos D1 Mini. if properly not set may trigger watchdog
 byte       pins[] = {  D1 ,  D2 ,  D3 ,  D4 ,  D5 ,  D6 ,  D7 ,  D8  };
 String pinnames[] = { "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8" };

and changing:



#if defined(ESP8266) || defined(ESP_H)
  ESP.wdtFeed();
#endif

to:


#if defined(ESP32)
  timerWrite(timer, 0); //reset timer (feed watchdog)
#endif
#elseif defined(ESP8266) || defined(ESP_H)
  ESP.wdtFeed(); //feed watchdog
#endif

will make nano esp32 work, but not checked yet.

**Comment by cyphunk** [comment]
thank you for trying this and reporting it. i am currently not able to test or conduct much coding work but if you submit a push request I could try to integrate your changes. But even if you cannot, it is still helpful that you reported it and others can find it here
